### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by halal-beef** [UsrBinLuna/wallpapers#2]
HTC WALLPAPER WHEN
HTC WALLPAPER WHEN
HTC WALLPAPER WHEN
HTC WALLPAPER WHEN
HTC WALLPAPER WHEN
HTC WALLPAPER WHEN
HTC WALLPAPER WHEN

**Comment by UsrBinLuna** [comment]
im going to block you from my repos
also how is this issue number 2

**Comment by halal-beef** [comment]
no

**Comment by team-orangeBlue** [comment]
NO THIS ISNT COMPLETE YET!!!!!!

https://github.com/UsrBinLuna/wallpapers/assets/63470411/33ad2c97-9d1a-482d-9536-5b8574972cc1

**Comment by team-orangeBlue** [comment]
also whoever is right now looking at what im doing on github please dont pay attention to this we're just playing around thank you

**Comment by UsrBinLuna** [comment]
https://www.youtube.com/watch?v=MuQ3S7y9pss

**Comment by oliver194** [comment]
wtf

**Comment by UsrBinLuna** [comment]
oliver why
