### ISSUE TITLE
im going to block you from my repos

### ISSUE THREAD

**Issue by team-orangeBlue** [UsrBinLuna/wallpapers#3]
im going to block you from my repos
also how is this issue number 2

_Originally posted by @UsrBinLuna in https://github.com/UsrBinLuna/wallpapers/issues/2#issuecomment-1900998008_
            
![img25](https://user-images.githubusercontent.com/63470411/298178791-24490b92-f825-4a82-94fc-b5926110fa2e.jpg)
![1600x1200_305315_ www ArtFile ru](https://user-images.githubusercontent.com/63470411/298178869-9647bc70-0e40-462b-a769-d43d05ee5a2a.jpg)
![img19](https://user-images.githubusercontent.com/63470411/298178896-d941b818-3d17-4fb0-bbe5-3cc46c407cb0.jpg)

Hi so there's a problem. Theres this cool russian wallpaper i found and it needs to be added. Please add. Thank you

**Comment by UsrBinLuna** [comment]
give me resolution and names and i will add

**Comment by team-orangeBlue** [comment]
the flower is 5120x2880 
the rectangles are 1920x1200
the ntv orb is 1600x1200

**Comment by UsrBinLuna** [comment]
duplicate issue, se #2

**Comment by team-orangeBlue** [comment]
okay
